openapi: 3.0.0
info:
  title: MyAPP
  description: "__ TODO: Diese Datei durch eine eigene API-Spezifikation ersetzen. __"
  contact:
    name: Dennis Schulmeister-Zimolong
    url: https://www.wpvs.de
    email: dhbw@windows3.de
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.de
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Beispiel
paths:
  /:
    get:
      tags:
      - Index
      summary: Wurzeladresse des Webservices
      description: Liefert eine HATEOAS-Übersicht aller collections
      operationId: index
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
                x-content-type: application/json

/example:
  get:
    tags:
    - Example
    summary: Suche nach Terminen
    description: Suche nach Terminen
    operationId: search-example
    parameters:
    - name: title
      in: query
      description: Titel der Arbeit
      required: false
      style: form
      explode: true
      schema:
        type: String
    - name: author
      in: query
      description: Autor der Arbeit
      required: false
      style: form
      explode: true
      schema:
        type: String
    - name: publisher
      in: query
      description: Publisher der Arbeit
      required: false
      style: form
      explode: true
      schema:
        type: String
    - name: year
      in: query
      description: Jahr der Arbeit
      required: false
      style: form
      explode: true
      schema:
        type: integer

  post:
    tags:
    - Example
    summary: Erstelle Terminen
    description: Suche nach Terminen
    operationId: create-example
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/example'
    responses:
      "201":
        description: Created
        headers:
          Location:
            schema:
              type: String
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/example'

 // 

  schemas:
    HATEOAS_Collection:
      title: HATEOAS-Links einer Collection
      type: object
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Resource:
      title: HATEOAS-Links einer Resource
      type: object
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Link:
      title: HATEOAS-Link
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string

    Example
      title: example
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HATEOAS_Resource'
        _id:
          type: string
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        year:
          type: integer
      required:
        - title
        - author
      example:
        _id: "621ff9a936997df5baba746e"
        title: "Fox"
        author: "Mulder"
        year: 2022
        publisher: "Michi"

  securitySchemes: {}
      
